spring:
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: sso

  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/0ae51e19-07c8-4e4b-bb6d-648ee58410f4/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/0ae51e19-07c8-4e4b-bb6d-648ee58410f4/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/0ae51e19-07c8-4e4b-bb6d-648ee58410f4/discovery/v2.0/keys
        registration:
          azure-client:
            provider: azure-ad
            client-id: 70584e59-8ebb-4c0f-bf18-2090a0f37874
            client-secret: 30c27af1-eade-4c26-94ce-68c7ace528e0
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid

server:
  error:
    include-stacktrace: never

  port: 8081

  shutdown: graceful
